version: '3.1'

services:

  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=facilita
      - POSTGRES_DB=facilita
    ports:
      - "5432:5432"